first_project/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns=[
    path('register/', views.register, name="register"),
    path('user_login/', views.user_login, name="user_login"),
]

first_project/first_app/urls.py
from django.conf.urls import url
from first_app import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index_2'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views as v1
from second_app import views as v2
from third_app import views as v3
from basic_app import views as v4

urlpatterns = [
    path('', v4.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('four/', include('third_app.urls')),
    path('polo/', include('first_app.urls')),
    path('second/', v2.index, name='index_2'),
    path('shutter/', v3.baka, name='baka'),
    path('admin/', admin.site.urls, name='index_5'),
    path('formpage/', v2.form_name_view, name='form_name'),
    path('logout/', v4.user_logout, name='logout'),
    path('special/', v4.special, name='special')
]

first_project/second_app/urls.py
from django.conf.urls import url
from first_app import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('formpage/', views.index, name='index'),
]

first_project/third_app/urls.py
from django.conf.urls import url
from third_app import views
from django.urls import path

app_name = 'third_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('baka/', views.baka, name='baka'),
    path('', views.linking, name='template_inheritance'),
]

first_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_project/second_app/models.py
from django.db import models

# Create your models here.

first_project/third_app/models.py
from django.db import models

# Create your models here.

first_project/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/second_app/forms.py
from django import forms
from django.core import validators


class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)    

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']

        if(len(email) <= 20):
            raise(forms.ValidationError("NOPE"))

first_project/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if(request.method == "POST"):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if(user_form.is_valid() and profile_form.is_valid()):
            salt = 'polo'
            user = user_form.save()
            passw = make_password(user.set_password, salt)
            user.set_password(str(passw))
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if('profile_pic' in request.FILES):
                profile.profile_pic = request.FILES['proflie_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if(request.method == 'POST'):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if(user):
            if(user.is_active):
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username :{} and password:{}".format(username, password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'basic_app/login.html', {})

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, AccessRecord, Webpage

# Create your views here.

def index(request):
    webpages_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_records':webpages_list}
    return render(request, 'first_app/index.html', context=date_dict)

first_project/second_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms

# Create your views here.

def index(request):
    return HttpResponse('<em>Second App</em>')

def form_name_view(request):
    form = forms.FormName()

    if(request.method == 'POST'):
        form = forms.FormName(request.POST)

        if(form.is_valid()):
            print("Validation SUCCESS")
            print("NAME:"+form.cleaned_data['name'])
            print("EMAIL:"+form.cleaned_data['email'])
            print("TEXT:"+form.cleaned_data['text'])

    return render(request, 'second_app/form_page.html', {'form':form})

first_project/third_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def linking(request):
    return render(request, 'third_app/base.html')

def other(request):
    return render(request, 'third_app/other.html')

def baka(request):
    return render(request, 'third_app/tp.html')

first_project/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <!-- <link>  LINK CSS--> 
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li class="navbar-brand"><a href="{% url 'index' %}">BRAND</a></li>
                    <li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li class="navbar-link"><a href="{% url 'basic_app:register' %}">Register</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

first_project/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

    <div class="jumbotron">
        <h1>OLO INDEX DESU</h1>
    </div>

{% endblock %}

first_project/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Please LOGIN</h1>
        <form action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label>Username:</label>
            <input type="text" name="username" placeholder="Enter Username">

            <label>Password:</label>
            <input type="text" name="password" placeholder="Enter Password">

            <input type="submit" name="" value="Login">
        </form>
    </div>>

{% endblock %}

first_project/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}

{% load static %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering</h1>
        {% else %}
            <h1>Register Here</h1>
            <h3>Fill out the form:</h3>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    </div>

{% endblock %}

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>FIRST APP</title>
        <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    </head>
    <body>
        <h1>CHIPOTLE!!</h1>
        {{ insert_me }}
        <!-- <img src="{% static "images/example.jpg" %}" alt="oops"> -->
        <div class="django">
            {% if access_records %}
            <table>
                <thead>
                    <th>Site Name</th>
                    <th>Date</th>
                </thead>

                {% for acc in access_records %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.date }}</td>
                </tr>
                {% endfor %}
            </table>
            {% else %}
                <p>NO ACCESS RECORDS FOUND</p>
            {% endif %}
        </div>
    </body>
</html>

first_project/templates/second_app/form_page.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>FIRST APP</title>
        <link rel="stylesheet" href="{% static "css/mystyle.css" %}"/>
    </head>
    <body>
        <h1>FORMPAGE</h1>
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>
    </body>
</html>

first_project/templates/third_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <!-- <link>  LINK CSS--> 
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li class="navbar-brand"><a href="{% url 'baka' %}">BRAND</a></li>
                    <li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
                    <li class="navbar-link"><a href="{% url 'third_app:other' %}">Other</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

first_project/templates/third_app/index.html
<!DOCTYPE html>
{% extends "third_app/base.html" %}
    {% block  body_block %}
        <h1>INDEX DESU!!</h1>
        tp desu
    {% endblock %}
    

first_project/templates/third_app/other.html
<!DOCTYPE html>
{% extends "third_app/base.html" %}
    {% block  body_block %}
        <h1>OTHER DESU!!</h1>
        Template inheritance
    {% endblock %}
    

first_project/templates/third_app/tp.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <!-- <link>  LINK CSS--> 
    </head>
    <body>
        <h3>BAKA</h3>
    </body>
</html>